# This is an example secrets.toml file for reference
# Copy this format exactly when adding secrets to Streamlit Cloud

[supabase]
url = "postgresql://postgres.yegrbbtxlsfbrlyavmbg:721AFFTNZmnQ3An7@yegrbbtxlsfbrlyavmbg.supabase.co:6543/postgres"

# Store-specific credentials 
[store_1]
name = "Laurel"
merchant_id = "4VZSM7038BKQ1"
access_token = "b9f678d7-9b27-e971-d9e4-feab8b227c96"

[store_2]
name = "Algiers"
merchant_id = "K25SHP45Z91H1" 
access_token = "fb51be17-f0c4-c58c-0e08-44bcd4bbc5ab"

[store_3]
name = "Hattiesburg"
merchant_id = "J3N08YKN8TSD1"
access_token = "5608c683-801e-d4cf-092d-abfc907eafcc" 